In [37]:
import pandas as pd
import numpy as np
import yaml

In [38]:
data = pd.read_csv('/home/timmiakov/repos/hse-materials/data/train.csv')

In [39]:
data

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

In [40]:
gender = [np.random.choice(np.arange(0, 2), p=[0.45, 0.55]) for _ in range(data.shape[0])]

In [41]:
len(gender)

159571

In [42]:
device = ['iphone', 'android', 'mac', 'linux', 'windows']
devices = [np.random.choice(device, p=[0.28, 0.42, 0.09, 0.02, 0.19]) for _ in range(data.shape[0])]

In [43]:
age_bin = ['0-18', '18-25', '25-35', '35-50', '50-65', '65+']
age_bins = [np.random.choice(age_bin, p=[0.15, 0.24, 0.28, 0.15, 0.09, 0.09]) for _ in range(data.shape[0])]

In [44]:
data['device'] = pd.Series(devices)
data['age'] = pd.Series(age_bins)

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate', 'device', 'age', 'need_ban'],
      dtype='object')

In [45]:
data

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,device,age
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,iphone,35-50
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,iphone,25-35
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,windows,35-50
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,android,0-18
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,android,18-25
...,...,...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0,mac,0-18
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0,windows,25-35
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0,android,50-65
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0,android,35-50
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0,windows,18-25

In [46]:
data['need_ban'] = data['toxic'] + data['severe_toxic'] + data['obscene'] + data['threat'] + data['insult'] + data['identity_hate']
data['need_ban'] = data['need_ban'].apply(lambda x: 1 if x > 0 else 0)

In [47]:
data

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,device,age,need_ban
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,iphone,35-50,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,iphone,25-35,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,windows,35-50,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,android,0-18,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,android,18-25,0
...,...,...,...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0,mac,0-18,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0,windows,25-35,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0,android,50-65,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0,android,35-50,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0,windows,18-25,0

In [48]:
data.to_csv('train_augmented.csv', index=False)

In [6]:
import yaml

data = {
    "kafka_configs": {
        'raw_data_configs': {
            'topic_name': 'raw_data',
            'consumer_config': {
                'bootstrap.servers': 'localhost:9095',
                'group.id': 'my_consumers'
            },
            'producer_config': {
                'bootstrap.servers': 'localhost:9095'
            },
        },
        'processed_data_configs': {
            'topic_name': 'processed_data',
            'data_processor_topic_config': {
                'bootstrap.servers': 'localhost:9095',
                'group.id': 'my_consumers'
            },
            'data_processor_config': {
                'bootstrap.servers': 'localhost:9095'
            }
        }
    }
}

In [7]:
with open('config.yaml', 'w') as file:
    yaml.dump(data, file)

In [5]:
import pandas as pd

In [6]:
data = pd.read_csv('data/train_augmented.csv')

In [7]:
data

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,device,age,need_ban
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,iphone,35-50,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,iphone,25-35,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,windows,35-50,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,android,0-18,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,android,18-25,0
...,...,...,...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0,mac,0-18,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0,windows,25-35,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0,android,50-65,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0,android,35-50,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0,windows,18-25,0

In [8]:
sample = data.iloc[0].to_dict()

In [27]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("s-nlp/roberta_toxicity_classifier")
model = AutoModelForSequenceClassification.from_pretrained("s-nlp/roberta_toxicity_classifier")

Some weights of the model checkpoint at s-nlp/roberta_toxicity_classifier were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [28]:
tokenized_text = tokenizer.encode(sample['comment_text'], return_tensors="pt")

In [29]:
tokenized_text

tensor([[    0,  9089, 11181,  1258, 50118,  7608,     5, 39708,   156,   223,
           127, 40952, 46206, 29082,  2426, 11232,    58, 41411,   116,   252,
          3559,    75, 24604, 28599,     6,    95,  6803,    15,   103,   272,
          1620,    71,    38,  2763,    23,   188,   469, 25678,    29, 26207,
             4,   178,  2540,   218,    75,  3438,     5, 27663,    31,     5,
          1067,  1842,   187,    38,   437,  3562,   122,     4,  5046,     4,
         22814,     4,  3170,     4,  2518,     2]])

In [ ]:
import time

infer_time = time.time()
model(tokenized_text)

SequenceClassifierOutput(loss=None, logits=tensor([[ 4.7666, -4.9104]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [22]:
sample

{'id': '0000997932d777bf',
 'comment_text': "Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
 'toxic': 0,
 'severe_toxic': 0,
 'obscene': 0,
 'threat': 0,
 'insult': 0,
 'identity_hate': 0,
 'device': 'iphone',
 'age': '35-50',
 'need_ban': 0}